# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "regelrett"
  tags:
  - "public"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skvis"
  system: "skjema-register"
  providesApis:
  - "regelrett-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "regelrett"
  links:
  - url: "https://github.com/kartverket/regelrett"
    title: "regelrett på GitHub"
spec:
  type: "repo"
  owner: "skvis"
  dependencyOf:
  - "component:regelrett"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "regelrett-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "skvis"
  definition: |
    openapi: "3.0.0"
    info:
        title: regelrett API
    paths:

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: skjema-register
  title: Skjemaregister
  labels:
    gcp-project-id: skvis-prod-9329
spec:
  owner: skvis
